---
title: "GLM Model After PCA"
author: "Hannah Damico"
date: "2022-11-28"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(lme4)
library(flextable)
library(pROC)
library(ROCR)
```

## Import Data

```{r}
mean_train <- read.csv("mean_train_frame.csv")
mean_test <- read.csv("mean_test_frame.csv")
```

## Normalize the Data

```{r}
mean_train_scaled <- mean_train_frame %>% mutate_at(
  vars(
    -subjid,
    -Interval,
    -Gender,
    -ICUType,
    -MechVent,
    -MechVent_cleaned,
    -in_hosp_death
  ),
  ~ scale(.) %>%  as.vector
)
```


```{r}
results <- glmer(as.factor(in_hosp_death) ~ Age + BUN + (1 + Interval | subjid),family = binomial(link = "logit"), data = mean_train, na.action = na.omit)
summary(results)
```

```{r}
prediction <- predict(results, mean_test, type = "response", allow.new.levels = TRUE)
auc(roc(mean_test$in_hosp_death, exp(prediction)))
auc <- 0.7558

pred <- prediction(exp(predict(results)), mean_train$in_hosp_death) 
perf <- performance(pred,"tpr","fpr")
plot(perf,colorize=TRUE)
abline(a=0, b= 1)
mylabel = bquote(bold(AUC) == .(format(auc, digits = 4)))
text(x = 0.65, y = 0.35, labels = mylabel)
```

```{r}
aucpr <- performance(pred,measure = "aucpr")
auc_PR <- aucpr@y.values[[1]]
```



## -------------------------------------------

```{r}
results2 <- glmer(as.factor(in_hosp_death) ~ Platelets + Urine + PaO2 + BUN + WBC + Age + (1 + Interval | subjid),family = binomial(link = "logit"), data = mean_train, na.action = na.omit)
summary(results2)
```


```{r}
prediction2 <- predict(results2, mean_test,type = "response",  allow.new.levels = TRUE)
auc(roc(mean_test$in_hosp_death, exp(prediction)))
auc2 <- 0.7558

pred2 <- prediction(exp(predict(results2)), mean_train$in_hosp_death) 
perf2 <- performance(pred2,"tpr","fpr")
```



```{r}
#get sensitivy and specificity
Observation <- mean_test$in_hosp_death
Roc_ <- pROC::roc(response = Observation, predictor = prediction2)

#Extract required data from ROC
TPR <- Roc_$sensitivities
FPR <- 1 - Roc_$specificities
AUC <- Roc_$auc[[1]]

#plot curve
ggplot()+
  geom_point(aes(x = FPR , y = TPR), col = "red") +
  labs(title = paste0("AUC = ", round(AUC,4))) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, NA)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, NA)) +
  theme_classic()
```


```{r}
aucpr2 <- performance(pred2, measure = "aucpr")
auc_PR2 <- aucpr2@y.values[[1]]
```





